image: docker:19.03.12

stages:
    - build
    - deploy

build_prod:
    stage: build
    script:
        - docker build 
            --build-arg LOGIN_API=$LOGIN_API
            --build-arg LOGIN_MICROSOFT=$LOGIN_MICROSOFT
            --build-arg LOGIN_CLIENT_ID=$LOGIN_CLIENT_ID
            --build-arg LOGIN_REDIRECT_URI=$LOGIN_REDIRECT_URI
            --build-arg LOGIN_SCOPE=$LOGIN_SCOPE
            --build-arg JWT_SECRET=$JWT_SECRET
            --build-arg HASURA_URL=$HASURA_URL
            --build-arg HASURA_SECRET=$HASURA_SECRET
            --build-arg API_URL=$API_URL
            --no-cache -t sip:latest --force-rm .
    environment:
        name: production
    only:
        - master
    tags:
        - prod-runner

deploy_prod:
    stage: deploy
    script:
        - docker stop sip && docker rm sip
        - docker run -d --name sip --network=paginaweb sip:latest
        - docker rmi $(docker images -f "dangling=true" -q)
    only:
        - master