image: docker:19.03.12

stages:
    - build
    - deploy

build_prod:
    stage: build
    script:
        - docker build
            --build-arg LOGIN_API=$LOGIN_API
            --build-arg LOGIN_MICROSOFT=$LOGIN_MICROSOFT
            --build-arg LOGIN_CLIENT_ID=$LOGIN_CLIENT_ID
            --build-arg LOGIN_SCOPE=$LOGIN_SCOPE
            --build-arg LOGIN_REDIRECT_URI=$LOGIN_REDIRECT_URI
            --build-arg LOGIN_GRANT_TYPE=$LOGIN_GRANT_TYPE
            --build-arg LOGIN_CLIENT_SECRET=$LOGIN_CLIENT_SECRET
            --build-arg JWT_SECRET=$JWT_SECRET
            --build-arg HASURA_URL=$HASURA_URL
            --build-arg HASURA_SECRET=$HASURA_SECRET
            --build-arg API_CEI=$API_CEI
            --build-arg RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED=$RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED
            --build-arg LOGIN_ALUMNOS_POSGRADO=$LOGIN_ALUMNOS_POSGRADO
            --build-arg APPSMITH_URL=$APPSMITH_URL
            --build-arg URL_BOLETAS_ESTUDIANTES_MATERIAS=$URL_BOLETAS_ESTUDIANTES_MATERIAS
            --build-arg URL_BOLETAS_INSCRIPCIONES=$URL_BOLETAS_INSCRIPCIONES
            --build-arg URL_PAGINA_POSGRADO=$URL_PAGINA_POSGRADO
            --build-arg APP_POSGRADO_CEI=$APP_POSGRADO_CEI
            --build-arg APP_SERVICIOS_ESCOLARES_CEI=$APP_SERVICIOS_ESCOLARES_CEI
            --build-arg APP_PRESIDENTE_CEI=$APP_PRESIDENTE_CEI
            --build-arg API_URL=$API_URL
            --no-cache -t sip:latest --add-host utilitics.ecosur.mx:10.1.5.112 --force-rm .
    environment:
        name: production
    only:
        - master
    tags:
        - prod-runner

build_dev:
    stage: build
    script:
        - docker build
            --build-arg DEV_LOGIN_API=$DEV_LOGIN_API
            --build-arg DEV_LOGIN_MICROSOFT=$DEV_LOGIN_MICROSOFT
            --build-arg DEV_LOGIN_CLIENT_ID=$DEV_LOGIN_CLIENT_ID
            --build-arg DEV_LOGIN_SCOPE=$DEV_LOGIN_SCOPE
            --build-arg DEV_LOGIN_REDIRECT_URI=$DEV_LOGIN_REDIRECT_URI
            --build-arg DEV_LOGIN_GRANT_TYPE=$DEV_LOGIN_GRANT_TYPE
            --build-arg DEV_LOGIN_CLIENT_SECRET=$DEV_LOGIN_CLIENT_SECRET
            --build-arg DEV_JWT_SECRET=$DEV_JWT_SECRET
            --build-arg DEV_HASURA_URL=$DEV_HASURA_URL
            --build-arg DEV_HASURA_SECRET=$DEV_HASURA_SECRET
            --build-arg DEV_API_CEI=$DEV_API_CEI
            --build-arg DEV_RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED=$DEV_RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED
            --build-arg DEV_LOGIN_ALUMNOS_POSGRADO=$DEV_LOGIN_ALUMNOS_POSGRADO
            --build-arg DEV_APPSMITH_URL=$DEV_APPSMITH_URL
            --build-arg DEV_URL_BOLETAS_ESTUDIANTES_MATERIAS=$DEV_URL_BOLETAS_ESTUDIANTES_MATERIAS
            --build-arg DEV_URL_BOLETAS_INSCRIPCIONES=$DEV_URL_BOLETAS_INSCRIPCIONES
            --build-arg DEV_URL_PAGINA_POSGRADO=$DEV_URL_PAGINA_POSGRADO
            --build-arg DEV_APP_POSGRADO_CEI=$DEV_APP_POSGRADO_CEI
            --build-arg DEV_APP_SERVICIOS_ESCOLARES_CEI=$DEV_APP_SERVICIOS_ESCOLARES_CEI
            --build-arg DEV_APP_PRESIDENTE_CEI=$DEV_APP_PRESIDENTE_CEI
            --build-arg DEV_API_URL=$DEV_API_URL
            --no-cache -t sip:latest --add-host utilitics.ecosur.mx:10.1.5.112 -f Dockerfile-dev --force-rm .
    environment:
        name: development
    only:
        - development
    tags:
        - dev-runner

deploy_prod:
    stage: deploy
    script:
        - docker stop sip && docker rm sip
        - docker run -d --name sip --network=paginaweb sip:latest
        - docker rmi $(docker images -f "dangling=true" -q)
    only:
        - master

deploy_dev:
    stage: deploy
    script:
        - docker stop sip && docker rm sip
        - docker run -d --name sip --network=infonomia sip:latest
        - docker rmi $(docker images -f "dangling=true" -q)
    environment:
        name: development
    only:
        - development
    tags:
        - dev-runner