module.exports = {
  env: {
    LOGIN_API: process.env.LOGIN_API,
    LOGIN_MICROSOFT: process.env.LOGIN_MICROSOFT,
    LOGIN_CLIENT_ID: process.env.LOGIN_CLIENT_ID,
    LOGIN_REDIRECT_URI: process.env.LOGIN_REDIRECT_URI,
    LOGIN_SCOPE: process.env.LOGIN_SCOPE,
    JWT_SECRET: process.env.JWT_SECRET,
    HASURA_URL: process.env.HASURA_URL,
    HASURA_SECRET: process.env.HASURA_SECRET,
    API_URL: process.env.API_URL,
    API_CEI: process.env.API_CEI,
    LOGIN_ALUMNOS_POSGRADO: process.env.LOGIN_ALUMNOS_POSGRADO,
    URL_BOLETAS_ESTUDIANTES_MATERIAS:
      process.env.URL_BOLETAS_ESTUDIANTES_MATERIAS,
    URL_BOLETAS_INSCRIPCIONES: process.env.URL_BOLETAS_INSCRIPCIONES,
    URL_PAGINA_POSGRADO: process.env.URL_PAGINA_POSGRADO,
    APPSMITH_URL: process.env.APPSMITH_URL,
    APP_POSGRADO_CEI: provess.env.APP_POSGRADO_CEI,
    APP_SERVICIOS_ESCOLARES_CEI: process.env.APP_SERVICIOS_ESCOLARES_CEI,
    API_URL: process.env.API_URL,
  },
};
